# Generated by Django 2.2.3 on 2019-08-14 19:01

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0020_remove_task_flipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveIntegerField()),
                ('points', cvat.apps.engine.models.FloatArrayField()),
                ('topic', models.TextField()),
                ('confidence', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
        ),
    ]
